name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Package version
      run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
    - name: Install modules
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run tsc && npm run build
    - name: Test
      run: npm test
    - name: Typings
      run: npm run typings:bundle
    - name: Package Prod
      run: npm run package:prod
    - run: npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}